import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { FlatCompat } from '@eslint/eslintrc';

const require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = require('node:path').dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

const baseRules = {
  'array-bracket-newline': ['error', { multiline: true, minItems: 2 }],
  'array-bracket-spacing': ['error', 'never'],
  'array-element-newline': ['error', { multiline: true, minItems: 3 }],
  'arrow-body-style': ['error', 'as-needed'],
  'arrow-parens': ['error', 'always'],
  'arrow-spacing': ['error', { before: true, after: true }],
  'block-scoped-var': 'error',
  'block-spacing': ['error', 'always'],
  'brace-style': ['error', '1tbs', { allowSingleLine: true }],
  'camelcase': ['error', { properties: 'never', ignoreDestructuring: false }],
  'comma-dangle': ['error', 'always-multiline'],
  'comma-spacing': ['error', { before: false, after: true }],
  'comma-style': ['error', 'last'],
  'complexity': ['warn', 20],
  'computed-property-spacing': ['error', 'never'],
  'consistent-return': 'error',
  'consistent-this': ['error', 'self'],
  'curly': ['error', 'multi-line'],
  'default-case': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-location': ['error', 'property'],
  'dot-notation': ['error', { allowKeywords: true }],
  'eol-last': ['error', 'always'],
  'eqeqeq': ['error', 'always'],
  'func-call-spacing': ['error', 'never'],
  'func-names': ['error', 'as-needed'],
  'func-style': ['error', 'expression'],
  'function-call-argument-newline': ['error', 'consistent'],
  'function-paren-newline': ['error', 'multiline-arguments'],
  'grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'guard-for-in': 'error',
  'implicit-arrow-linebreak': ['error', 'beside'],
  'indent': ['error', 2, { SwitchCase: 1, ImportDeclaration: 1, ignoreComments: true }],
  'key-spacing': ['error', { beforeColon: false, afterColon: true }],
  'keyword-spacing': ['error', { before: true, after: true }],
  'line-comment-position': ['error', { position: 'above' }],
  'linebreak-style': ['error', 'unix'],
  'lines-around-comment': ['error', { beforeBlockComment: true, allowArrayStart: true }],
  'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
  'max-classes-per-file': ['error', 1],
  'max-depth': ['warn', 4],
  'max-len': ['error', { code: 140, ignoreComments: true, ignoreTemplateLiterals: true }],
  'max-lines': ['warn', { max: 800, skipComments: true }],
  'max-lines-per-function': ['warn', { max: 120, skipBlankLines: true, skipComments: true }],
  'max-nested-callbacks': ['warn', 5],
  'max-params': ['warn', 5],
  'max-statements': ['warn', { max: 40 }],
  'multiline-comment-style': ['error', 'starred-block'],
  'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
  'newline-after-var': ['error', 'always'],
  'newline-before-return': 'error',
  'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-await-in-loop': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-confusing-arrow': ['error', { allowParens: true }],
  'no-console': ['warn', { allow: ['error', 'warn', 'info'] }],
  'no-continue': 'error',
  'no-div-regex': 'error',
  'no-duplicate-imports': ['error', { includeExports: true }],
  'no-else-return': ['error', { allowElseIf: false }],
  'no-empty-function': ['error', { allow: ['arrowFunctions'] }],
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-extra-semi': 'error',
  'no-floating-decimal': 'error',
  'no-implicit-coercion': 'error',
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-inline-comments': 'off',
  'no-invalid-this': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-mixed-operators': [
    'error',
    {
      groups: [
        ['&', '|', '^', '~', '<<', '>>', '>>>'],
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
      allowSamePrecedence: false,
    },
  ],
  'no-multi-assign': 'error',
  'no-multi-spaces': ['error', { ignoreEOLComments: true }],
  'no-multi-str': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': ['error', { props: true }],
  'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
  'no-promise-executor-return': 'error',
  'no-proto': 'error',
  'no-restricted-exports': 'off',
  'no-restricted-globals': [
    'error',
    { name: 'event', message: '请勿直接使用全局event对象' },
    { name: 'fdescribe', message: '测试环境禁止使用fdescribe' },
  ],
  'no-restricted-imports': [
    'error',
    {
      patterns: ['../*'],
      paths: [
        {
          name: 'fs',
          importNames: ['promises'],
          message: '请使用模块化封装的文件系统方法',
        },
      ],
    },
  ],
  'no-restricted-properties': [
    'error',
    {
      object: 'document',
      property: 'write',
      message: '禁止使用 document.write，避免XSS风险',
    },
  ],
  'no-restricted-syntax': [
    'error',
    {
      selector: 'WithStatement',
      message: '禁止使用with语句',
    },
    {
      selector: "CallExpression[callee.object.name='console'][callee.property.name=/^(debug)$/]",
      message: '请使用logger模块进行调试输出',
    },
  ],
  'no-return-assign': ['error', 'always'],
  'no-return-await': 'off',
  'no-script-url': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow': ['error', { hoist: 'functions', allow: ['resolve', 'reject', 'done', 'next'] }],
  'no-template-curly-in-string': 'error',
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-undefined': 'error',
  'no-underscore-dangle': ['error', { allow: ['__APP_LOGGER__', '__APP_STORAGE__'] }],
  'no-unneeded-ternary': 'error',
  'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
  'no-unused-vars': ['error', { args: 'after-used', ignoreRestSiblings: true }],
  'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': ['error', { allowAsStatement: false }],
  'no-warning-comments': ['warn', { terms: ['todo', 'fixme'], location: 'anywhere' }],
  'object-curly-newline': ['error', { multiline: true, consistent: true }],
  'object-curly-spacing': ['error', 'always'],
  'object-property-newline': ['error', { allowMultiplePropertiesPerLine: false }],
  'object-shorthand': ['error', 'always'],
  'one-var': ['error', 'never'],
  'one-var-declaration-per-line': ['error', 'always'],
  'operator-assignment': ['error', 'always'],
  'operator-linebreak': ['error', 'before'],
  'padded-blocks': ['error', { blocks: 'never', classes: 'never', switches: 'never' }],
  'prefer-arrow-callback': ['error', { allowNamedFunctions: false }],
  'prefer-const': ['error', { destructuring: 'all' }],
  'prefer-destructuring': ['error', { object: true, array: false }],
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'warn',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'quote-props': ['error', 'as-needed'],
  'quotes': ['error', 'single', { avoidEscape: true }],
  'radix': ['error', 'always'],
  'require-await': 'error',
  'require-unicode-regexp': 'warn',
  'rest-spread-spacing': ['error', 'never'],
  'semi': ['error', 'always'],
  'semi-spacing': ['error', { before: false, after: true }],
  'semi-style': ['error', 'last'],
  'sort-imports': [
    'error',
    {
      ignoreCase: false,
      ignoreDeclarationSort: false,
      ignoreMemberSort: false,
      memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
    },
  ],
  'sort-keys': ['warn', 'asc', { caseSensitive: true, natural: false }],
  'space-before-blocks': ['error', 'always'],
  'space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
  'space-in-parens': ['error', 'never'],
  'space-infix-ops': 'error',
  'space-unary-ops': ['error', { words: true, nonwords: false }],
  'spaced-comment': ['error', 'always', { block: { balanced: true } }],
  'strict': ['error', 'never'],
  'switch-colon-spacing': ['error', { after: true, before: false }],
  'symbol-description': 'error',
  'template-curly-spacing': ['error', 'never'],
  'template-tag-spacing': ['error', 'never'],
  'yoda': ['error', 'never'],
};

const securityRules = {
  'no-new-require': 'error',
  'no-path-concat': 'error',
  'node/no-callback-literal': 'error',
  'node/no-exports-assign': 'error',
  'node/no-missing-import': 'off',
  'node/no-unpublished-import': 'off',
  'node/no-process-env': 'warn',
  'node/no-sync': ['warn', { allowAtRootLevel: true }],
  'security/detect-child-process': 'error',
  'security/detect-eval-with-expression': 'error',
  'security/detect-new-buffer': 'error',
  'security/detect-non-literal-fs-filename': 'error',
  'security/detect-non-literal-regexp': 'error',
  'security/detect-non-literal-require': 'error',
  'security/detect-object-injection': 'off',
  'security/detect-possible-timing-attacks': 'warn',
  'security/detect-pseudoRandomBytes': 'error',
};

const testOverrides = {
  files: ['**/*.test.js', '**/__tests__/**/*.js'],
  rules: {
    'max-lines-per-function': 'off',
    'no-unused-expressions': 'off',
    'no-console': 'off',
  },
};

const nodeConfig = {
  files: ['src/**/*.js', 'apps/**/*.js', 'models/**/*.js'],
  languageOptions: {
    ecmaVersion: 2023,
    sourceType: 'module',
  },
  plugins: {
    security: require('eslint-plugin-security'),
    node: require('eslint-plugin-n'),
    import: require('eslint-plugin-import'),
  },
  rules: {
    ...baseRules,
    ...securityRules,
    'import/no-extraneous-dependencies': ['error', { packageDir: [__dirname] }],
    'import/no-unresolved': 'error',
    'import/no-cycle': ['warn', { maxDepth: 2 }],
    'import/newline-after-import': ['error', { count: 1 }],
    'import/order': [
      'error',
      {
        groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
        pathGroupsExcludedImportTypes: ['builtin'],
        alphabetize: { order: 'asc', caseInsensitive: true },
        newlines-between: 'always',
      },
    ],
    'import/prefer-default-export': 'off',
    'import/no-useless-path-segments': ['error', { noUselessIndex: true }],
  },
};

const webConfig = {
  files: ['web/**/*.js', 'web/**/*.html'],
  languageOptions: {
    ecmaVersion: 2023,
    sourceType: 'module',
    globals: {
      window: 'readonly',
      document: 'readonly',
      fetch: 'readonly',
      EventSource: 'readonly',
    },
  },
  rules: {
    ...baseRules,
    'max-len': ['error', { code: 160, ignoreTemplateLiterals: true, ignoreStrings: true }],
    'no-alert': 'off',
    'no-console': 'off',
  },
};

const prettierConfig = {
  files: ['**/*.js'],
  ignores: ['node_modules/**', 'logs/**'],
  rules: {
    'prettier/prettier': [
      'error',
      {
        printWidth: 100,
        tabWidth: 2,
        singleQuote: true,
        trailingComma: 'all',
        bracketSpacing: true,
        semi: true,
        useTabs: false,
        quoteProps: 'as-needed',
        arrowParens: 'always',
      },
    ],
  },
  plugins: {
    prettier: require('eslint-plugin-prettier'),
  },
};

const configs = [
  ...compat.extends('airbnb-base', 'prettier'),
  nodeConfig,
  webConfig,
  testOverrides,
  prettierConfig,
];

export default configs;
